feat(wasm): add consensus logic
sedaprotocol/seda-rust pull request #110
Opened 2023-03-30 09:21 UTC by mariocao

PR co-authored by @FranklinWaller 

## Motivation

This PR adds functionality for consensus but also fixes some problems that were identified during the implementation.

## Explanation of Changes

This PR includes the first basic consensus logic for batch and p2p handling among other things that were required in the way:
- Refactor regarding `KeyPair` and how they were configured and used.
- Implement batch consensus logic
- Implement slot leader logic
- Implement p2p handler for receiving batch messages

## Testing

Unfortunately, right now there is no automated integration or end-to-end tests. Therefore, this PR has been manually tested.

Testing instructions using `near-cli` (Javscript version, not rust):

### 1. Build contracts

Before building the contracts, we have to comment out the following verifications in `contracts/src/batch.rs`:

Assertion for disallowing empty batches:
```
// require the data request accumulator to be non-empty
// assert!(
//     !self.data_request_accumulator.is_empty(),
//     "Data request accumulator is empty"
// );
```

Verification of aggregated public key using external `bn254` library instead of provided host functions (subsidized):
```
// let aggregate_public_key_reconstructed = signers.iter().skip(1).fold(
//     PublicKey::from_compressed(self.active_nodes.get(&signers[0]).unwrap().bn254_public_key).unwrap(),
//     |acc, signer| {
//         assert!(self.committees[0].contains(signer), "Node is not part of the committee");
//         let signer_public_key =
//             PublicKey::from_compressed(self.active_nodes.get(signer).unwrap().bn254_public_key).unwrap();
//         acc + signer_public_key
//     },
// );
// assert!(
//     aggregate_public_key_reconstructed.to_compressed().unwrap() == aggregate_public_key,
//     "Invalid aggregate public key"
// );
```

This needs to be commented out because otherwise the transaction runs out of gas (>300 Tgas).

```
make build-contracts
```

### 2. Deploy contract using `near-cli` Javascript command

It will deploy the contract to testnet and with a automatically generated account id.

```
near dev-deploy target/wasm32-unknown-unknown/release/seda_mainchain.wasm
```

### 3. Initialize smart contract

Initialize the contracts by calling the `init()` function. For example, it can be done by using the same development account from previous step.

```
near call <dev_account_id> new '{"dao":"<dev_account_id>","initial_supply":"1000000000000000000000000000","metadata":{"spec":"ft-1.0.0","name":"SEDA Token","symbol":"SEDA","icon":null,"reference":null,"reference_hash":null,"decimals":24},"committee_size":'2',"random_seed":"531540567384302522"}' --account-id dev_account_id
```

### 4. Setup node operators

Using the all-in-one CLI command `delegate setup`, new nodes can be configured as:

```
SIGNER_ACCOUNT_ID=<my-account.tesnet> ACCOUNT_SECRET_KEY=<secret_key> VALIDATOR_SECRET_KEY=<my_secret_key> make run-build-delegate setup -- <contract_account_id>
```

### 5. Start the first epoch in the contract

This is done by calling `process_epoch()` function in the contract.

```
near call <contract_id> process_epoch --account-id <account_id>
```

In this case because we are using a dev account, we can set `account_id` as the `contract_id`.

### 6. Run multiple nodes

Run multiple nodes to have a working committee (in my tests there were 3).

For example for node 1:
```
SEDA_SECRET_KEY=<KEY_NODE_1> make run-build-all run -- --p2p-server-address /ip4/127.0.0.1/tcp/50001
```

The config file `config.toml` should be properly configured to use the `contract_id` we just deployed.

### 7. (Optional) Add peers manually

Sometimes, in my local environment peer discovery was not finding the new peers using mDNS. Therefore, I had to add the peers manually.

For example to force the discovery of 3 nodes with consecutive TCP ports:
```
target/debug/seda node peers add /ip4/127.0.0.1/tcp/50001
target/debug/seda node peers add /ip4/127.0.0.1/tcp/50002
target/debug/seda node peers add /ip4/127.0.0.1/tcp/50003
```

2023-03-30 15:37 UTC, gluax requested changes
Looking good so far! There are some things we can definitely clean up a little, though. And a few food for thought items relevant to the changes in this PR.

2023-03-30 15:37 UTC, gluax commented on chains/src/near_chain.rs
> +        signer_keypair: Vec<u8>,
and here as well.

2023-03-30 15:37 UTC, gluax commented on cli/src/cli/commands/node/get/node.rs
> +        let contract_id = if let Some(contract_id) = self.contract_id {
We had something like `to_contract_id` on the config before. Now we could define a `PartialNodeConfig` and say `.to_partial_node_config` given the user config and inputs, which we already have here.

2023-03-30 15:37 UTC, gluax commented on runtime/core/src/storage/in_memory_adapter.rs
> +    fn contains_key(&self, key: &str) -> bool {
Do we need this when `get` already returns an `Option`? Or maybe it's to check you aren't overwriting a field?

2023-03-30 15:37 UTC, gluax commented on runtime/sdk/src/wasm/memory.rs
> +        _ => panic!("Bn254 verify returned invalid bool in u8: {}", result),
Better to use `unreachable!(...)` here instead of `panic!(...)`. Would provide a better message that something *really* went wrong. Mostly because as far as I can tell it should actually be unreachable.

2023-03-30 15:37 UTC, gluax commented on wasm/consensus/src/tasks/batch.rs
>  use seda_runtime_sdk::{
maybe with all these imports at this point we should do `use seda_runtime_sdk::{*, wasm::*}`.

2023-03-30 15:37 UTC, gluax commented on wasm/consensus/src/tasks/batch.rs
> -    log!(Level::Debug, "Batch Step 1");
I personally think we should keep some debug logs here. So we know we hit this function last if that makes sense. Users won't get debug logs in, so there's only benefits to having more for debug purposes imo.

2023-03-30 15:37 UTC, gluax commented on wasm/consensus/src/tasks/batch.rs
> +            serde_json::from_str(&batch_string).expect("Cannot convert `merkle_root` json to `ComputeMerkleRootResult`")
Instead of converting to a `String` then doing `serde_json::from_str` you can do `serde_json::from_slice`. Saves a computation step.

2023-03-30 15:37 UTC, gluax commented on wasm/consensus/src/tasks/batch.rs
> +    // Case 1. Check if it was already processed
I think it would make for cleaner code to move this logic to the `batch` type itself(in a method) and pass whatever data it additionally needs.

2023-03-30 15:37 UTC, gluax commented on wasm/consensus/src/tasks/batch.rs
> +    let current_slot_leader = match batch.current_slot_leader {
Same thing here, should be a method on the type, for cleanliness imo.

2023-03-30 15:37 UTC, gluax commented on wasm/consensus/src/tasks/bridge.rs
> +                get_oracle_contract_id().as_str(), // TODO: Currently panics
Can we use memory read on this value in the first step with a `TODO` above it? I think better to have functioning logic. Especially since we have a CLI command to debug this logic.

2023-03-30 15:37 UTC, gluax commented on wasm/consensus/src/tasks/p2p.rs
> +        match message {
Fine for now, but this logic should move to a similar pattern like our `task.handle` so as we add more in the future the function logic doesn't get too cluttered.

2023-03-30 15:37 UTC, gluax commented on wasm/consensus/src/types/batch_signature.rs
> +pub static EMPTY_SHA256: [u8; 32] = [
Sorry I don't remember but does not allow us to make static `Vec` types?

2023-03-30 15:37 UTC, gluax commented on wasm/consensus/src/types/batch_signature.rs
> +        serde_json::from_str(&json_str).expect("Invalid stored `BatchSignatureStore` object")
Same here could use `serde_json::from_slice` and skip the `String` step.

2023-03-30 15:37 UTC, gluax commented on wasm/consensus/src/message.rs
> +pub struct BatchMessage {
i.e. that logic before should be moved to a method on this type.

2023-03-30 15:37 UTC, gluax commented on wasm/consensus/src/message.rs
> +pub enum Message {
Then this should also have a call `handle` that consumes `self` and bubbles down.

2023-03-31 13:36 UTC, mariocao commented on cli/src/cli/commands/node/get/node.rs
> +        let contract_id = if let Some(contract_id) = self.contract_id {
In this case it is not directly the node config, because I still need to derive the public key from the Ed25519 keypair and encode it in hex. Anyhow, I think I managed to do it a little bit better.

2023-03-31 13:42 UTC, mariocao commented on cli/src/cli/commands/node/get/nodes.rs
> +        let contract_id = if let Some(contract_id) = self.contract_id {
Same as before

2023-03-31 13:46 UTC, mariocao commented on config/src/configs/delegate.rs
> +        let validator_master_key = merge_config_cli!(self, cli_options, validator_secret_key, Ok(String::new()))?;
That was not my code 😅

2023-03-31 13:56 UTC, mariocao commented on runtime/core/src/imports.rs
> +/// Reads the value from memory as byte array and sends the number of bytes to
Opps...it was copy-pasted.

2023-03-31 14:07 UTC, mariocao commented on wasm/consensus/src/tasks/batch.rs
> -    log!(Level::Debug, "Batch Step 1");
It was replaced not removed by `log!(Level::Debug, "[BatchTask] Starting task for contract id: {contract_id}");`

2023-03-31 14:14 UTC, mariocao commented on wasm/consensus/src/types/batch_signature.rs
> +pub static EMPTY_SHA256: [u8; 32] = [
I changed it to a constant:

```
const EMPTY_SHA256: [u8; 32] = [
    227, 176, 196, 66, 152, 252, 28, 20, 154, 251, 244, 200, 153, 111, 185, 36, 39, 174, 65, 228, 100, 155, 147, 76,
    164, 149, 153, 27, 120, 82, 184, 85,
];
```

2023-03-31 14:26 UTC, mariocao commented on wasm/consensus/src/tasks/p2p.rs
> +        match message {
Agree, we can do it once we have more message types :)

2023-03-31 14:40 UTC, gluax commented on cli/src/cli/commands/node/get/node.rs
> +        let contract_id = if let Some(contract_id) = self.contract_id {
I personally still think it's cleaner to have that logic in a function on the type. Also if we need similar logic in the future it's easy to just call that function then.

2023-03-31 14:40 UTC, gluax commented on config/src/configs/delegate.rs
> +        let validator_master_key = merge_config_cli!(self, cli_options, validator_secret_key, Ok(String::new()))?;
Oops my bad haha

2023-03-31 14:45 UTC, gluax commented on wasm/consensus/src/tasks/batch.rs
> -    log!(Level::Debug, "Batch Step 1");
But that's in the handle function. Not in batch step 1. That assumes we will always make it to batch step 1 which isn't necessarily true.

2023-03-31 17:57 UTC, mariocao commented
I just tried out the code and updated the testing instructions. 🤯

2023-04-02 13:31 UTC, jamesondh approved these changes
Working for me, but for future reference (during end-to-end testing) I had to set two config values manually to get it to work with my localnet script, when they should be using `SEDA_NEAR_RPC_URL` in env or `chain_rpc_url` in `config.toml`:

1. `RPC_URL` in `DelegateConfigInner`
2. `chain_rpc_url` in `test_config()`

If you want to test this on localnet, run the script `sh deploy-localnet.sh --committeeSize 2 --testAccounts true` on branch `feat/deploy-localnet` and follow the instructions to process the epoch and start the nodes once the setup is complete.

2023-04-03 08:33 UTC, Thomasvdam approved these changes

2023-04-03 08:33 UTC, Thomasvdam commented on crypto/src/test.rs
Perhaps add a test to verify that changing the index produces a different key?

2023-04-03 09:07 UTC, merged