Implement token deposits for nodes
sedaprotocol/seda-rust pull request #67
Opened 2023-02-06 19:59 UTC by jamesondh

## Motivation

(Write your motivation here)

## Explanation of Changes

(Write your explanation here)

## Testing

(Write your test plan here)

## Related PRs and Issues

(Link your related PRs and Issues here)

2023-02-09 09:25 UTC, FranklinWaller commented on contracts/mainchain/src/consts.rs
> +pub const EPOCH_DELAY_FOR_ELECTION: u64 = 2;
Both MINIMUM_STAKE and EPOCH_DELAY_FOR_ELECTION are not constants, they should always be modifiable by the DAO

2023-02-09 09:39 UTC, FranklinWaller requested changes

2023-02-09 09:39 UTC, FranklinWaller commented on contracts/mainchain/src/node_registry.rs
> +    pub socket_address:      String,
Would call this a multi_addr to comply with libp2p

2023-02-09 09:39 UTC, FranklinWaller commented on contracts/mainchain/src/node_registry.rs
> +    pub socket_address:      String,
Same here

2023-02-09 09:39 UTC, FranklinWaller commented on contracts/mainchain/src/node_registry.rs
> +            );
I'm not sure if you can validate a multi_addr. The addresses we use in libp2p look like: /ip4/198.51.100.0/tcp/4242/p2p/QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N (https://docs.libp2p.io/concepts/fundamentals/addressing/) but can be longer/shorter

2023-02-09 09:39 UTC, FranklinWaller commented on contracts/mainchain/src/node_registry.rs
> +        // update account
Maybe write a todo here, a withdrawal should be requested and only after x amount of epochs it's allowed to fully withdraw

2023-02-09 10:17 UTC, mariocao commented on contracts/mainchain/src/data_request_test.rs
> +            .attached_deposit(2_140_000_000_000_000_000_000) // required for post_data_request()
Where does this storage deposit value comes from?

2023-02-09 10:20 UTC, mariocao commented on contracts/mainchain/src/node_registry.rs
> +    pub socket_address:      String,
Then maybe we should mention that it follows the `libp2p` address format.

2023-02-09 10:22 UTC, mariocao commented on contracts/mainchain/src/node_registry.rs
> +            );
I wouldn't because there is no way of preventing nodes setting up addresses that don't exist, are offline or belong to other peers.

2023-02-09 13:33 UTC, jamesondh commented on contracts/mainchain/src/data_request_test.rs
> +            .attached_deposit(2_140_000_000_000_000_000_000) // required for post_data_request()
Yes, pretty much trial and error to calculate it: if not enough storage is attached, the transaction will revert and tell you how much you need. The manage_storage_deposit macro handles this

2023-02-09 23:18 UTC, gluax requested changes

2023-02-09 23:18 UTC, gluax commented on contracts/mainchain/src/dao_test.rs
> +mod tests {
don't need this `mod tests` block here since you have `mod dao_test` in the `lib.rs`. May need to move the `cfg` line to above that statement in the `lib.rs` file though.

2023-02-09 23:18 UTC, gluax commented on contracts/mainchain/src/node_registry_test.rs
> +mod tests {
Same here.

2023-02-09 23:18 UTC, gluax commented on contracts/seda-token/Cargo.toml
> +near-sdk = { workspace = true, features = ["legacy", "unit-testing"] }
What's required from `legacy`? We should try to avoid whatever `near` deems as legacy as much as possible IMO, in case they ever deprecate something or etc.

2023-02-09 23:18 UTC, gluax commented on contracts/tests/README.md
> +```make build-wasm
I think this has since been updated to `make-contracts` right?

2023-02-10 14:08 UTC, jamesondh commented on contracts/seda-token/Cargo.toml
> +near-sdk = { workspace = true, features = ["legacy", "unit-testing"] }
not sure, but removing it didn't seem to bork anything 🤷

2023-02-13 14:24 UTC, mariocao approved these changes

2023-02-13 14:24 UTC, FranklinWaller approved these changes

2023-02-14 14:19 UTC, merged