Add ability to remotely add/remove/list peers
sedaprotocol/seda-rust pull request #68
Opened 2023-02-08 14:55 UTC by FranklinWaller

## Motivation

A node operator should be able to add/remove/list peers on the fly through the CLI. This implements those functions

## Explanation of Changes

Move known_peers up a level so we can pass it to the RPC and P2PServer through Arc<RwLock<_>>. Also added the commands in the cli package and implement the P2PCommand (mpsc channel)

## Testing

1. Start two nodes
2. Use `seda node peers list` to see the connected peers
3. Use `seda node peers remove <PEER_ID>` to remove a peer (PEER_ID can be found by using list)
4. Use `seda node peers list` to see that it has been removed
5. Use `seda node peers add <MULTI_ADDR>` to add the peer back again (MULTI_ADDR) can be found in the logs from the other node. (looks like "/ip4/172.19.0.2/tcp/44681")

2023-02-08 22:08 UTC, gluax requested changes
This looks good to me, but can you run `seda generate` command to update the CLI readme?

2023-02-09 10:08 UTC, mariocao commented on cli/src/cli/commands/node/peers/add.rs
> +    pub multi_addr: String,
Add comment for the CLI doc :)

2023-02-09 10:08 UTC, mariocao commented on cli/src/cli/commands/node/peers/remove.rs
> +    pub peer_id: String,
Same here :)

2023-02-09 10:25 UTC, mariocao approved these changes

2023-02-09 10:55 UTC, Thomasvdam approved these changes
Beautiful 👍

2023-02-09 12:48 UTC, merged