feat(contracts): implement basic `post_signed_batch` method
sedaprotocol/seda-rust pull request #82
Opened 2023-03-01 15:41 UTC by jamesondh

## Motivation

(Write your motivation here)

## Explanation of Changes

(Write your explanation here)

## Testing

(Write your test plan here)

## Related PRs and Issues

(Link your related PRs and Issues here)

2023-03-02 18:06 UTC, gluax requested changes

2023-03-02 18:06 UTC, gluax commented on contracts/mainchain/src/batch.rs
> +        for signer in signers.iter().skip(1) {
Can we write a comment here explaining why we skip 1?

2023-03-02 18:06 UTC, gluax commented on contracts/tests/Cargo.toml
> +rand = "0.8.5"
From the workspace?

2023-03-03 20:04 UTC, gluax approved these changes

2023-03-03 20:15 UTC, mennatabuelnaga approved these changes

2023-03-03 20:24 UTC, mariocao approved these changes

2023-03-06 01:05 UTC, merged