feat(contracts): deposit on a ed25519 key
sedaprotocol/seda-rust pull request #91
Opened 2023-03-12 17:27 UTC by jamesondh

WIP: functionality and tests are done, just need to clean up `depositors` by using nested collection types instead of a Vec

## Motivation

(Write your motivation here)

## Explanation of Changes

(Write your explanation here)

## Testing

(Write your test plan here)

## Related PRs and Issues

(Link your related PRs and Issues here)

2023-03-13 21:14 UTC, gluax requested changes

2023-03-13 21:14 UTC, gluax commented on contracts/src/test_utils.rs
> +pub fn bob() -> TestAccount {
It looks like a lot of these functions are similar, we could probably boil it down to one function. I.e. `make_test_account(pk: &str, pk_bytes: &[u8], account_id: &str)`.

Then if possible could make `static` instances of the `TestAccount` types. If that can't be done cause certain methods aren't constant we could do the following:

Declare a new type `pub struct TestAccounts;`, then make those `TestAccount` instances associated consts.

Either way cleans up some repetitive code and lets us have constants rather than recreating these every time.

2023-03-14 08:34 UTC, FranklinWaller commented on contracts/src/node_registry.rs
> +            self.token.accounts.insert(&depositor_account_id, &new_user_balance);
These two lines seems like they are going to be used often (also with "transferring" tokens) Might be good to have somewhere an internal util function that handles these things automatically.

2023-03-14 08:34 UTC, FranklinWaller commented on contracts/src/node_registry.rs
> +                    b"d".as_slice(),
I'm seeing a lot of these prefixes, can we have them in one file containing constants? using just one letter might accidentally collide in the future. Having them in one file gives a clear overview what we are using

2023-03-14 10:22 UTC, FranklinWaller commented on contracts/src/node_registry.rs
> +            .expect("Node does not exist");
Can we make this "Node {ed25519_public_key} does not exist"? It helps a lot

2023-03-14 18:45 UTC, jamesondh commented on contracts/src/node_registry.rs
> +                    b"d".as_slice(),
Moved this to `MainchainStorageKeys` in `lib.rs` which is a common pattern

2023-03-15 08:52 UTC, FranklinWaller approved these changes

2023-03-15 12:31 UTC, mariocao commented on contracts/src/node_registry.rs
> +            self.mint(&depositor_account_id, amount);
I think that minting/burning for staking/unstaking is weird.
It affects the total token supply and it will make things harder to track (I think).

Question: does it not make more sense to transfer the tokens to the contract?

2023-03-15 14:22 UTC, jamesondh commented on contracts/src/node_registry.rs
> +            self.mint(&depositor_account_id, amount);
The FungibleToken standard only exposes `ft_transfer()` which transfers from `env::predecessor_account_id()` to a receiver, so we have to use our own internal transfer function anyways. So actually transferring tokens in `self.tokens` would only add an extra step, since we already track the balance in the `Node` info and globally with `self.last_total_balance`. With this pattern though, it's probably a good idea to override `ft_total_supply()` from the FungibleToken standard and set it to `self.token.total_supply + self.last_total_balance`.

2023-03-16 00:53 UTC, jamesondh commented on contracts/src/test_utils.rs
> +pub fn bob() -> TestAccount {
I created a `make_test_account` function but not sure if making them static/const is still applicable since I reused Menna's key generation test here

2023-03-16 08:41 UTC, FranklinWaller commented on contracts/src/node_registry.rs
> +            self.mint(&depositor_account_id, amount);
It's true we track it internally but from an explorer point of view (near blocks for example)it would show those tokens are lost somehow. I think it'd be good to still have in the token mapping show that this account id has the staked tokens

2023-03-16 19:22 UTC, gluax approved these changes

2023-03-16 19:23 UTC, gluax commented on contracts/src/test_utils.rs
> +pub fn bob() -> TestAccount {
Yea, this looks much cleaner to me!

2023-03-16 21:13 UTC, merged