feat: init committee selection
sedaprotocol/seda-rust pull request #92
Opened 2023-03-13 23:22 UTC by mennatabuelnaga

## Motivation

(Write your motivation here)

## Explanation of Changes

(Write your explanation here)

## Testing

(Write your test plan here)

## Related PRs and Issues

(Link your related PRs and Issues here)

2023-03-14 15:10 UTC, gluax requested changes

2023-03-14 15:10 UTC, gluax commented on contracts/Cargo.toml
> +getrandom = { version = "0.2", features = ["custom"], default-features = false}
`workspace = true`?

2023-03-14 15:10 UTC, gluax commented on contracts/src/batch_test.rs
> +    let deposit_amount = U128(100_000_000_000_000_000_000_000_000);
Is this a placeholder for now, or some default value? If it's the latter we should store it in a const variable.

2023-03-14 15:10 UTC, gluax commented on contracts/src/batch_test.rs
>      for committee in contract.get_committees() {
`contract.get_committees().into_inter().for_each(|comittee| assert_eq!(comittee.len(), contract.config.committee_size));`

2023-03-14 15:10 UTC, gluax commented on contracts/src/consts.rs
> +pub const INIT_MINIMUM_STAKE: u128 = 100_000_000_000_000_000_000_000_000; // 1 SEDA
Ah, is this the same as the `deposit_amount` we've been using? Then we should use this variable instead of writing out the number every time :).

2023-03-15 09:00 UTC, FranklinWaller approved these changes

2023-03-15 12:17 UTC, mariocao approved these changes

2023-03-15 17:32 UTC, merged