Feat/common module
sedaprotocol/seda-rust pull request #94
Opened 2023-03-15 17:23 UTC by gluax

## Motivation

To have commonly used Data Structures from a single source rather than re-defining them.

## Explanation of Changes

This creates a new module within our workspace, `seda-common`, and we define the commonly used structures there.
This module exposes a `cli` flag that provides clap bindings.

The `contracts` and `cli` modules now use these as a single source of truth. 

The update command has been changed to be a struct enum in a single place so that it also works for the CLI.

**NOTES**: 

- The register command needs the private key and signature. I have dummy values there since we don't store the `KeyPair` on the  `NodeConfig` in this branch. Once that change is in, we can address that.
- Similarly, the `unregister` command has been removed from the contract but is to be added back in. So, for now, I'm not making any changes to it, and when we add that command back in, we can fix it.

## Testing

By hand.

## Related PRs and Issues

#85 adds the `KeyPair` in the `NodeConfig`, so that PR can make the changes to fix the `register` command if this one is merged first. Or we can do it in a separate follow-up PR. 
#91 Has changes made to some of these structs in its PR, so there will be conflicts one way or another after one is merged.

2023-03-15 19:30 UTC, jamesondh requested changes

2023-03-15 19:30 UTC, jamesondh commented on seda_sk
should be .gitignored?

2023-03-16 08:46 UTC, FranklinWaller commented on seda_sk
Did a secret key just got leaked 😛

2023-03-16 16:26 UTC, mariocao commented on common/src/node/get.rs
> +
```suggestion
```

2023-03-16 16:27 UTC, mariocao commented on common/src/node/mod.rs
> +pub struct HumanReadableNode {
Maybe `NodeInfo`?
```suggestion
pub struct NodeInfo {
```

2023-03-16 17:08 UTC, gluax commented on seda_sk
whoops! it was ignored in my other branch but not this one 😅

2023-03-18 01:15 UTC, jamesondh approved these changes

2023-03-20 09:22 UTC, FranklinWaller approved these changes

2023-03-20 23:47 UTC, merged